#:kivy 1.0

<IndexerCore>:
    canvas:
        Rectangle:
            pos: self.center_x-5, 0
            size: 10, self.height

    Button:
        text: "Hello World"
        font_size: 14

    Label:
        font_size: 70
        center_x: root.width / 4
        top: root.top - 50
        text: "0"

    Label:
        font_size: 70
        center_x: root.width * 3 / 4
        top: root.top - 50
        text: "0"